### ISSUE TITLE
Escaping $ and $ in raw should not get parsed as math

### ISSUE THREAD

**Issue by vhf** [Rokt33r/remark-math#11]
`remark-math` has a quite painful parsing bug due to this regular expression: https://github.com/Rokt33r/remark-math/blob/2445b979253214997174092785589386d79892e5/packages/remark-math/inline.js#L6

How to reproduce:

    $foo\$

Explanation: This gets matched by the regex because it starts with `$`, ends with `$`, and between the starting `$` and ending `$` there's no `\$`.

Also an issue:

    $foo`$`

Here are failing test cases:

```js
it('must escape a dollar with back slash', () => {
  const processor = remark()
    .use(math)

  const targetText = '$\\alpha\\$'

  const ast = processor.parse(targetText)
  expect(ast).toMatchObject(u('root', [
    u('paragraph', [
      u('text', '$\\alpha'),
      u('text', '$')
    ])
  ]))
})

it('must not parse a raw dollar', () => {
  const processor = remark()
    .use(math)

  const targetText = '$\\alpha`$`'

  const ast = processor.parse(targetText)
  expect(ast).toMatchObject(u('root', [
    u('paragraph', [
      u('text', '$'),
      u('text', '\\alpha'),
      u('text', '$')
    ])
  ]))
})
```

**Comment by Rokt33r** [comment]
Published! Thanks for the contributing.

**Comment by vhf** [comment]
Awesome, thanks for the quick response!
