### ISSUE TITLE
Bump peer dep for remark-parse

### ISSUE THREAD

**Issue by viggyfresh** [Rokt33r/remark-math#14]
Hi there! I've been using `remark-math` on a React/Redux/Electron/TypeScript project with `remark-parse` at >=v4.0.0 with no (known) issues. I hadn't really been paying attention to Yarn warnings, but I came across this when setting up a new dev machine:

warning "remark-math@1.0.1" has unmet peer dependency "remark-parse@>=3.0.0".

Any chance you could bump the peer deps on this repo?

**Comment by Rokt33r** [comment]
Thanks to notice. I'll fix it in 24 hours.

**Comment by viggyfresh** [comment]
Bumping this - I'm more than happy to file a PR if that helps, but I figure @Rokt33r will need to tag a release anyway

**Comment by Rokt33r** [comment]
I'm really sorry. I've forgotten do it. I'll do it now.

**Comment by Rokt33r** [comment]
@viggyfresh Could you create a PR for this? I'm not sure how should I fix this. Is it enough to bump the version of remark-parse to `>=v4.0.0`?

**Comment by viggyfresh** [comment]
I think the convention is to have different version ranges for different major versions...for example:

```
"react": "^16.0.0 || ^15.0.1 || ^0.14",
```

So in this case, `"remark-parse": ">=3.0.0 || >= 4.0.0"`?

**Comment by Rokt33r** [comment]
@viggyfresh Done. Let me know if you have still the problem.
https://github.com/Rokt33r/remark-math/commit/a64fccfa695b1f7dcc9954c949041d73cc61c888

**Comment by viggyfresh** [comment]
Hi there,

Oddly enough, this is still causing grief even with v1.0.2. This might be a bug in Yarn's dependency resolution, but could you try this instead?

```
"peerDependencies": {
    "remark-parse": "^3.0.0 || ^4.0.0"
},
```

**Comment by Rokt33r** [comment]
I've published again.
https://github.com/Rokt33r/remark-math/commit/7e334a60436639827b96ac520bcb7614bc4d0d08

**Comment by viggyfresh** [comment]
Thanks @Rokt33r for all the efforts...turns out we were chasing a red herring:

https://github.com/yarnpkg/yarn/issues/4850
https://github.com/yarnpkg/yarn/issues/4765

In any case, I think we're all set on the `remark-math` side! thanks again.

**Comment by Rokt33r** [comment]
Glad to hear that! 😄 Thanks for the contributing!
