### ISSUE TITLE
subscripts and superscripts broken with latest katex 0.9.0 alpha 2

### ISSUE THREAD

**Issue by blueberryapple** [Rokt33r/remark-math#15]
with the latest version of katex, the output of
```latex
$\int_a^c \exp(x^2)$
```
looks like
![image](https://user-images.githubusercontent.com/9259833/34510634-83457100-f00a-11e7-9d34-d9696d6ebfa0.png)

**Comment by Rokt33r** [comment]
RemarkMath is just using API of katex. It should be better to write another issue in katex repository.

Btw, I assume this is because you forget providing `<!DOCTYPE html>`.

**Comment by blueberryapple** [comment]
It's not an issue with katex, because [with vanilla katex the output is fine.](https://codepen.io/anon/pen/GyvJxO?editors=1000) It's also not an issue of not including the doctype because I did include it. However, if I downgrade to katex 0.7.1 then it renders correctly. This is why I created an issue in remark math instead of the katex repo.

**Comment by Rokt33r** [comment]
As I said, RemarkMath is just using KaTeX API. It doesn't do anything for actual rendering, so I cannot help you.

And, it is still alpha. Please submit another issue to KaTeX.
