### ISSUE TITLE
remark-parse 5.0.0

### ISSUE THREAD

**Issue by unindented** [Rokt33r/remark-math#22]
Is there anything preventing the project from accepting `remark-parse` `5.0.0` as a peer dependency?

**Comment by wooorm** [comment]
@unindented Why would you like a defined peer dependency?

**Comment by unindented** [comment]
@wooorm you already have one: https://github.com/Rokt33r/remark-math/blob/b4fb470af9b957312ee0faa2885310accda93db5/packages/remark-math/package.json#L25

I was asking if there was anything preventing from adding `5.0.0` there.
