### ISSUE TITLE
Could not find a declaration file for module 'remark-math'

### ISSUE THREAD

**Issue by SurjitSahoo** [Rokt33r/remark-math#29]
I'm trying to use it as a plugin for react-markdown. I get the following error  
`Could not find a declaration file for module 'remark-math'`  
I tried to install types for it. using `npm install @types/remark-math` but I get 404 error. Please make it available

**Comment by pacocom** [comment]
I have same problems Could not find a declaration file for module 'remark-behead'. 'c:/Users/Francisco/Documents/baikal-global/developers/node_modules/remark-behead/index.js' implicitly has an 'any' type.
  Try `npm install @types/remark-behead` if it exists or add a new declaration (.d.ts) file containing `declare module 'remark-behead';`

**Comment by wooorm** [comment]
@pacocom hi, welcome! The chances of getting help on an in loses issue are very slim. I suggest opening a new issue on the project mentioned in your error: remark-behead
