### ISSUE TITLE
remark-math-katex

### ISSUE THREAD

**Issue by Rokt33r** [Rokt33r/remark-math#4]
I think the usage of `remark-math-katex` should be like the following.

```js
const remark = require('remark')
const math = require('remark-math')
const katex = require('remark-math-katex')

const remarkProcessor = remark()
  .use(math)
  .use(katex)
  .use(html)
```

The problem is that `remark-math-katex` can not access `options.handlers` of `remark-html`.

Of course, if I provide `data.hName` and `data.hChildren`, this can be solved easily.

But here comes another problem. I think `math` and `inlineMath` should use `value` as its content, instead of `children: [{type: 'text', value: value}]`, just like `code` and `inlineCode`.

If we keep using `children`, some transformers might misunderstand its content as a `text` node of `paragraph`.

So, I think handlers of `remark-html` should be exposed to inject handlers from other plugins.

## Alternative Ideas

Of course, there are some alternatives like the below.

### Provide katex handlers into options of `remark-html`

```js
const remark = require('remark')
const math = require('remark-math')
const katex = require('remark-math-katex')

const remarkProcessor = remark()
  .use(math)
  .use(html, {
    handlers: {
      inlineMath: ~~,
      math: ~~
    }
  })
```

PRO: No need to modify `remark-html`
CON: Bad usability

### Transform math nodes

```js
const visit = require('unist-util-visit')
const katex = require('katex')

module.exports = function plugin (p, opts = {}) {
  if (opts.throwOnError == null) opts.throwOnError = false
  return function transform (node) {
    visit(node, 'inlineMath', function (inlineMath) {
      inlineMath.type = 'html'
      inlineMath.value = ~~
    })
    visit(node, 'math', function (math) {
      math.type = 'html'
      math.value = ~~
    })

    return node
  }
}
```

PRO: No need to modify `remark-html`
CON: AST would be compromised(`remark-html` has no side effect to parsed AST)

**Comment by Rokt33r** [comment]
@wooorm Could you tell me which solution is the ideal? Sorry for annoying.

**Comment by wooorm** [comment]
I think remark-math should just deal with math in markdown, adding support for `inlineMath` (`{type: 'inlineMath', value: 'x'}`) and `math` nodes (`{type: 'math', value: 'x'}`).

So remark-math deals with markdown only: parsing from markdown, compiling to markdown.

Then, it’s probably a good idea to add `hName`, and `hProperties` to those math nodes.
As that would result in remark-vdom, remark-html, remark-rehype to see those nodes.
This does mean syntax-tree/mdast-util-to-hast/issues/11 should be solved first.
Now we have `{type: 'inlineMath', value: 'x', data: {hName: 'span', hProperties: {className: ['math']}}}`

Finally, after some thinking, I suggest creating a [rehype](https://github.com/wooorm/rehype) plugin instead: rehype-katex. How remark-html works, is essentially first remark-rehype and then rehype-stringify. If you’d directly run remark-rehype, then rehype-katex, and then rehype-stringify.
I think rehype-katex should transform `<span class="inline-math">...</span>` to  `<span class="katex">...</span>`!

---

So in the end you’ll get something like this:

```js
var unified = require('unified');
var markdown = require('remark-parse');
var math = require('remark-math');
var remark2rehype = require('remark-rehype');
var katex = require('rehype-katex');
var html = require('remark-html');

var doc = unified()
  .use(markdown)
  .use(math)
  .use(remark2rehype)
  .use(katex)
  .use(html)
  .process('# Alpha\n\nBravo $$x$$ Charlie')
  .toString();
```

Yields:

```html
<h1>Alpha</h1>
<p>Bravo <span class="katex">...</span> Charlie</p>
```

**Comment by Rokt33r** [comment]
Applied #3

**Comment by episodeyang** [comment]
@wooorm given that we use a rehype plugin for the generation of the html, I think we should remove the `h<>` keys in the ast. They are redundant and sometimes incorrect, for example when an exposed `math` node is exposed directly without a wrapping paragraph. In that case there should be a wrapping paragraph.

* This is based on the idea that `math` nodes are in fact inline display blocks that has to be wrapped by a block node.

**Comment by wooorm** [comment]
@episodeyang Sure, makes sense!
