### ISSUE TITLE
Add projects to list of plugins

### ISSUE THREAD

**Issue by wooorm** [Rokt33r/remark-math#7]
* remark: https://github.com/wooorm/remark/blob/master/doc/plugins.md
* rehype: https://github.com/wooorm/rehype/blob/master/doc/plugins.md

**Comment by Rokt33r** [comment]
I've forgotten it. Thanks for reminding. 😄

**Comment by wooorm** [comment]
👍 take your time :)

**Comment by Rokt33r** [comment]
I create PRs. It is okay to edit those description. :smile:

- https://github.com/wooorm/remark/pull/243
- https://github.com/wooorm/rehype/pull/9
